dist: buster
sudo: false

language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - pypy3

addons:
  apt:
    packages:
      - poppler-utils

before_install:
  - sudo apt install -y poppler-utils

install:
  - pip install codecov
  - pip install tox
  - pip install tox-travis
script:
  - coverage --version
  - tox

#after_success:
#  - coverage report -m
